server:
  port: 8087
  servlet:
    context-path: '/cooperativa/v1/'

spring:
  application:
    name: cooperativa
  datasource:
    url: jdbc:postgresql://localhost:5434/cooperativa
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
