version: '3.8'

services:

  cooperativa-db:
    container_name: cooperativapostgres
    image: postgres:alpine
    restart: always
    volumes:
      - ./docker-postgres-init.sql:/docker-entrypoint-initdb.d/docker-postgres-init.sql
    environment:
      POSTGRES_MULTIPLE_DATABASES: cooperativa
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
