name: Maven Build and Test

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Build with Maven
      run: mvn clean install

    - name: Run Tests
      run: mvn test

    - name: Check build status
      run: |
        if [[ success() == 'true' ]]; then
          echo "Build and tests successful"
          exit 0
        else
          echo "Build or tests failed"
          exit 1
        fi
